# Generated by Django 4.1 on 2022-08-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
