# Generated by Django 4.1 on 2022-08-16 03:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
