# Generated by Django 4.1 on 2022-09-03 11:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=25, verbose_name='Titulo')),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo')),
                ('btn', models.CharField(max_length=10, verbose_name='Boton')),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principales',
            },
        ),
    ]
