# Generated by Django 4.1 on 2022-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='btn',
            field=models.CharField(max_length=20, verbose_name='Boton'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='cuerpo',
            field=models.CharField(max_length=100, verbose_name='Cuerpo'),
        ),
    ]
