# Generated by Django 4.1 on 2022-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_principal_btn_alter_principal_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='cuerpo',
            field=models.CharField(max_length=300, verbose_name='Cuerpo'),
        ),
    ]
