# Generated by Django 4.1 on 2022-09-03 22:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='respuesta',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Respuesta'),
        ),
    ]
