# Generated by Django 4.1 on 2022-09-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_faq_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pregunta',
            field=models.CharField(max_length=200, verbose_name='Pregunta'),
        ),
    ]
