# Generated by Django 4.1 on 2022-08-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=256)),
                ('server_name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transferred_bytes', models.BigIntegerField(default=0)),
                ('limit_bytes', models.BigIntegerField(default=250000000)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='OutlineKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField(verbose_name='Llave ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('password', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('port', models.IntegerField()),
                ('method', models.CharField(max_length=256, verbose_name='Metodo')),
                ('access_url', models.CharField(max_length=256, verbose_name='Acceso Url')),
                ('used_bytes', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovpn.outlineserver', verbose_name='server')),
            ],
            options={
                'verbose_name': 'Llave',
                'verbose_name_plural': 'Llaves',
            },
        ),
    ]
