# Generated by Django 4.1 on 2022-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlineserver',
            name='limit_bytes',
            field=models.BigIntegerField(default=250000000000),
        ),
    ]
