# Generated by Django 4.1 on 2022-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0004_alter_outlinekey_access_url_alter_outlinekey_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinekey',
            name='limit_data',
            field=models.IntegerField(blank=True, default=0, verbose_name='Limite'),
            preserve_default=False,
        ),
    ]
