# Generated by Django 4.1 on 2022-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0005_outlinekey_limit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinekey',
            name='limit_data',
            field=models.BigIntegerField(blank=True, verbose_name='Limite'),
        ),
    ]
