# Generated by Django 4.1 on 2022-08-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0007_alter_outlinekey_access_url_alter_outlinekey_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinekey',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='outlineserver',
            name='is_deleted',
        ),
    ]
