# Generated by Django 4.1 on 2022-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0008_remove_outlinekey_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinekey',
            name='limit_data',
            field=models.BigIntegerField(default=0, verbose_name='Limite'),
            preserve_default=False,
        ),
    ]
