# Generated by Django 4.1 on 2022-08-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovpn', '0010_alter_outlinekey_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinekey',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_fora', to='ovpn.outlineserver'),
        ),
    ]
